version: '3'

services:

  localstack:
    image: localstack/localstack-full
    container_name: AWSstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "8080:8080"
      - "8081:8081"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/localstack/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./aws:/docker-entrypoint-initaws.d

#   minio:
#     container_name: minio
#     image: minio/minio
#     command: [server, /data]
#     environment: *env   
#     ports:
#       - 9000:9000
#     volumes:
#       - minio:/data
#     deploy:
#         replicas: 1
#         restart_policy:
#             condition: on-failure



# volumes: 
#   minio:
